FROM python:3.12-slim 

WORKDIR /app 

RUN pip install uv

COPY app.py . 
COPY uv.lock . 
COPY pyproject.toml . 

RUN uv sync --locked

EXPOSE 8501 

CMD ["uv", "run", "streamlit", "run", "app.py", "--server.port=8501", "--server.address=0.0.0.0"]