FROM python:3.12-slim 

WORKDIR /app 

COPY app.py . 
COPY pyproject.toml . 

RUN pip install torch --extra-index-url https://download.pytorch.org/whl/cpu
RUN pip install . 

EXPOSE 8501 

CMD ["streamlit", "run", "app.py", "--server.port=8501", "--server.address=0.0.0.0"]